FROM tomcat:9-jdk11

LABEL maintainer="Mario Gay <magabor6@gmail.com>"

ENV GEOSERVER_VERSION 2.21.2
ENV GEOSERVER_DATA_DIR /var/local/geoserver
ENV GEOSERVER_INSTALL_DIR /usr/local/geoserver
ENV GEOSERVER_EXT_DIR /var/local/geoserver-exts

ENV GEOSERVER_PATH=/geoserver

# Tomcat environment
ENV CATALINA_OPTS "-server -Djava.awt.headless=true \
	-Xms1024m -Xmx4096m -XX:+UseConcMarkSweepGC -XX:NewSize=48m \
	-DGEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR} \
	-Dcom.sun.management.jmxremote=true"

# Disable CSRF to allow editing layers in web UI 
ENV GEOSERVER_CSRF_DISABLED=true

# Microsoft fonts
RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections \
	&& set -x \
	&& apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -yq ttf-mscorefonts-installer unzip \
	&& rm -rf /var/lib/apt/lists/* \
# GeoServer
	&& mkdir -p /usr/local/tomcat/conf/Catalina/localhost/ && \
	echo "<Context path=\"${GEOSERVER_PATH}\" docBase=\"/usr/local/geoserver\"></Context>" > /usr/local/tomcat/conf/Catalina/localhost/geoserver.xml \
	&& mkdir ${GEOSERVER_DATA_DIR} \
	&& cd ${GEOSERVER_INSTALL_DIR} \
	&& wget http://sourceforge.net/projects/geoserver/files/GeoServer/${GEOSERVER_VERSION}/geoserver-${GEOSERVER_VERSION}-war.zip \
	&& unzip geoserver-${GEOSERVER_VERSION}-war.zip \
	&& unzip geoserver.war \
	&& mv data/* ${GEOSERVER_DATA_DIR} \
	&& rm -rf geoserver-${GEOSERVER_VERSION}-war.zip geoserver.war target *.txt \
# Oracle
	&& cd ${GEOSERVER_INSTALL_DIR}/WEB-INF/lib \
	&& wget http://sourceforge.net/projects/geoserver/files/Geoserver/${GEOSERVER_VERSION}/geoserver-${GEOSERVER_VERSION}-oracle-plugin.zip \
	&& unzip -o geoserver-${GEOSERVER_VERSION}-oracle-plugin.zip \
	&& rm geoserver-${GEOSERVER_VERSION}-oracle-plugin.zip *.txt *.html \
# Enable CORS
	&& sed -i '\:</web-app>:i\
	<filter>\n\
	    <filter-name>CorsFilter</filter-name>\n\
	    <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>\n\
	    <init-param>\n\
		<param-name>cors.allowed.origins</param-name>\n\
		<param-value>*</param-value>\n\
	    </init-param>\n\
	    <init-param>\n\
		<param-name>cors.allowed.methods</param-name>\n\
		<param-value>GET,POST,HEAD,OPTIONS,PUT</param-value>\n\
	    </init-param>\n\
	</filter>\n\
	<filter-mapping>\n\
	    <filter-name>CorsFilter</filter-name>\n\
	    <url-pattern>/*</url-pattern>\n\
	</filter-mapping>' ${GEOSERVER_INSTALL_DIR}/WEB-INF/web.xml \
# Create tomcat user to avoid root access. 
	&& addgroup --gid 1099 tomcat && useradd -m -u 1099 -g tomcat tomcat \
	&& chown -R tomcat:tomcat . \
	&& chown -R tomcat:tomcat ${GEOSERVER_DATA_DIR} \
	&& chown -R tomcat:tomcat ${GEOSERVER_INSTALL_DIR} \
	&& export CATALINA_OPTS \
	&& export GEOSERVER_CSRF_DISABLED

COPY --chown=tomcat:tomcat server.xml /usr/local/tomcat/conf
COPY --chown=tomcat:tomcat tomcat-users.xml /usr/local/tomcat/conf/
COPY --chown=tomcat:tomcat manager.xml /usr/local/tomcat/conf/Catalina/localhost
COPY --chown=tomcat:tomcat probe.war /usr/local/tomcat/webapps

COPY start.sh /usr/local/bin/start.sh

ENTRYPOINT [ "/bin/sh", "/usr/local/bin/start.sh"]

VOLUME ["${GEOSERVER_DATA_DIR}", "${GEOSERVER_EXT_DIR}"]

EXPOSE 8080
